# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec para NEXA Productivity Hub v2.0."""

import os
from pathlib import Path

block_cipher = None
root = Path(SPECPATH)

a = Analysis(
    [str(root / "hub" / "app.py")],
    pathex=[str(root)],
    binaries=[],
    datas=[
        (str(root / "plugins"), "plugins"),
        (str(root / "modules"), "modules"),
        (str(root / "assets"), "assets"),
        (str(root / "hub" / "infrastructure" / "migrations"), "hub/infrastructure/migrations"),
    ],
    hiddenimports=[
        "hub",
        "hub.__init__",
        "hub.app",
        "hub.demo_data",
        "hub.core",
        "hub.core.auth_service",
        "hub.core.audit_service",
        "hub.core.catalog_service",
        "hub.core.config_service",
        "hub.core.feed_service",
        "hub.core.health_check",
        "hub.core.knowledge_service",
        "hub.core.metrics_collector",
        "hub.core.notification_service",
        "hub.core.opportunity_tracker",
        "hub.core.plugin_registry",
        "hub.core.project_service",
        "hub.core.request_service",
        "hub.core.search_engine",
        "hub.core.service_container",
        "hub.core.workflow_engine",
        "hub.core.report_service",
        "hub.core.app_state_service",
        "hub.core.favorites_service",
        "hub.infrastructure",
        "hub.infrastructure.database",
        "hub.infrastructure.logging_setup",
        "hub.models",
        "hub.models.application",
        "hub.models.audit",
        "hub.models.favorite",
        "hub.models.knowledge",
        "hub.models.metrics",
        "hub.models.notification",
        "hub.models.opportunity",
        "hub.models.plugin",
        "hub.models.post",
        "hub.models.project",
        "hub.models.recent",
        "hub.models.request",
        "hub.models.user",
        "hub.ui",
        "hub.ui.shell",
        "hub.ui.auth",
        "hub.ui.auth.login_view",
        "hub.ui.admin.admin_center_view",
        "hub.ui.admin.app_audit_view",
        "hub.ui.admin.automation_proposal_view",
        "hub.ui.admin.audit_log_view",
        "hub.ui.admin.failure_detail_view",
        "hub.ui.admin.feed_view",
        "hub.ui.admin.help_request_view",
        "hub.ui.admin.impact_dashboard_view",
        "hub.ui.admin.issue_report_view",
        "hub.ui.admin.knowledge_view",
        "hub.ui.admin.notification_view",
        "hub.ui.admin.rating_view",
        "hub.ui.admin.requests_view",
        "hub.ui.admin.user_management_view",
        "hub.ui.app_viewer.app_viewer",
        "hub.ui.catalog.catalog_view",
        "hub.ui.common",
        "hub.ui.common.design",
        "hub.ui.dashboard",
        "hub.ui.dashboard.dashboard_view",
        "hub.ui.dashboard.enhanced_dashboard_view",
        "hub.ui.reports",
        "hub.ui.reports.reports_center_view",
        "hub.ui.search.search_view",
        "plugins.horas_extras.gui.widget",
        "plugins.sap_automation.gui.widget",
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebEngineCore",
        "PySide6.QtSvg",
        "PySide6.QtNetwork",
        "openpyxl",
        "pandas",
        "numpy",
        "PySide6.QtCharts",
        "PIL",
        "yaml",
        "win32com",
        "win32api",
        "win32con",
        "win32timezone",
        "pythoncom",
        "concurrent.futures",
        "difflib",
        "unicodedata",
        "tempfile",
        "csv",
        "hashlib",
        "urllib.request",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tests",
        "pytest",
        "pytest_cov",
        "ruff",
        "mypy",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="NEXA Hub",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="NEXA Hub",
)



